### PR TITLE
Fix single variable assignment in deeper scopes

### LINKED ISSUE #73: Issue with variable assignment within different scopes
Variables are not correctly assigned if they are defined in a certain level and their value is changed in a different one. For example, consider the following instruction:
```
@instruction
def test(signer: Signer, number: f64):
   myboolean=True
   newnumber=1.0
   if number > 0.0:
      myboolean=False
      newnumber=10.0
      print(f'Your boolean is {myboolean}. Extra number: {newnumber}.')
   print(f'Your number is {number}.')
   print(f'Your boolean is {myboolean}. Extra number: {newnumber}.')
```

When the previous instruction is executed with the number 5.0 as an input, the output is
```
Program log: Instruction: Test
Program log: Your boolean is false. Extra number: 10.
Program log: Your number is 5.
Program log: Your boolean is true. Extra number: 1.
```
which is clearly an undesired behaviour.

### PR DESCRIPTION
**Pull request by ameliatastic**
[Explanation here.](https://github.com/ameliatastic/seahorse-lang/issues/73#issuecomment-1339765566)

Closes #73

### CODE REVIEW

**Comment by ameliatastic** [comment]
(Note that I know this isn't done yet, this will cause errors when a variable is re-assigned in the same scope. PR is here so that more eyes can get on this.)

**Comment by mcintyre94** [comment]
Good to see the CI picking up these changes! Would it be worth adding an example that does a bit more scope stuff - maybe including lists and also tuples like you were talking about on the issue?

File: src/core/compile/check/mod.rs [hunk 1]
```diff
@@ -1070,11 +1076,8 @@ impl<'a> Context<'a> {
             ast::StatementObj::TyAssign { target, ty, value } => {
                 match (as_assignment_target(target), value) {
                     (Some(target), Some(value)) => {
-                        let undeclared = self.get_undeclared(&target, loc)?;
-                        self.assign_order.push(Assign::Declare {
-                            undeclared,
-                            target: target.clone(),
-                        });
+                        let assign_i = self.assign_order.len();
+                        self.assign_order.push(Assign::Placeholder);
```
Comment (mcintyre94) [inline src/core/compile/check/mod.rs:1080]: How come we need to do this? If I'm understanding correctly `assign_i` is the index that `Placeholder` will be pushed at, and then later we do `self.assign_order[assign_i] = Assign::Declare {...}`. How come we can't just do `self.assign_order.push(Assign::Declare { ... }` instead of pushing the placeholder first?

Comment (ameliatastic) [reply src/core/compile/check/mod.rs:1080]: It's more of me being safe + a little bit lazy. The `Assign` can only be created after the inner expressions of the statement are checked, and I didn't want to think too hard to see whether more assignments could be generated by expressions. Pretty sure they can't be though, and if not, then you're right and this can be refactored.
